services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documentalyze_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
# Removed Networks section - Compose will manage networking via the root include