services:
  backend:
    build: .
    container_name: documentalyze_backend
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./nodemon.json:/usr/src/app/nodemon.json # Mount nodemon config
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads # Reverted container path
      - ../dl_lit:/usr/src/app/dl_lit # Mount the python scripts
    command: npm run dev